sudo: true

language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.7
          dist: xenial
          services:
              - xvfb

        - os: linux
          sudo: required
          python: 3.6
          dist: xenial
          services:
              - xvfb

        - os: linux
          sudo: required
          python: 3.5
          dist: xenial
          services:
              - xvfb

        - os: osx
          language: generic
          
        - os: linux
          python: 3.7-dev
          dist: xenial
          services:
              - xvfb
        - os: linux
          python: 3.8-dev
          dist: xenial
          services:
              - xvfb
        - os: linux
          python: nightly
          dist: xenial
          services:
              - xvfb
    allow_failures:
        - os: linux
          sudo: required
          python: 3.5
          dist: xenial
          services:
              - xvfb
        
addons:
  apt:
    packages: &BASE_PACKAGES
      - libnotify-bin
      - libcairo2-dev
      - gir1.2-gtk-3.0
      - libpango1.0-dev
      - libxcb-xtest0-dev
      - libxcb-icccm4-dev
      - libxcb-randr0-dev
      - libxcb-keysyms1-dev
      - libxcb-xinerama0-dev
      - libdbus-1-dev
      - libxdg-basedir-dev
      - libstartup-notification0-dev
      - imagemagick
      - libxcb1-dev
      - libxcb-shape0-dev
      - libxcb-util0-dev
      - libx11-xcb-dev
      - libxcb-cursor-dev
      - libxcb-xkb-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev

install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip3 install -r requirements.txt --user ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then pip install -r requirements.txt ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then python3 setup.py install          ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then python setup.py install         ; fi

before_script:
  - "export DISPLAY=:99.0"
  - "export QT_DEBUG_PLUGINS=1"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 5 # give xvfb some time to start

script:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then python3 -m gopem --test    ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then python -m gopem --test   ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip3 install -r dev-requirements.txt --user ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then pip install -r dev-requirements.txt ; fi
  - chmod +x rsrc/static_test.sh
  - bash rsrc/static_test.sh
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then python3 -m gopem --test    ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then python -m gopem --test   ; fi
